version: '3.5'

networks:
  main:
    name: itu-minitwit-network

services:

  minitwitimage:
    image: ${DOCKER_USERNAME}/minitwit-app
    container_name: minitwit
    networks:
      - main
    depends_on:
      - itusqlimage
    ports:
        - '5000:5000'

  itusqlimage:
    image: ${DOCKER_USERNAME}/minitwit-mysql
    container_name: minitwit_mysql
    networks:
      - main
    ports:
      - '3306:3306'
    environment:
        - MYSQL_ROOT_PASSWORD=root
