version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - setup_remote_docker
#      - add_ssh_keys:
#          fingerprints:
#            - "2f:aa:68:28:2a:7d:9b:64:8b:32:61:94:00:30:8c:d5"
      - run:
          name: Build and push Docker image
          command: |
            echo "LOGIN"
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            echo "BUILD"
            docker build -t $DOCKER_USERNAME/minitwit-app:latest . -f Dockerfile-minitwit
            docker build -t $DOCKER_USERNAME/minitwit-mysql:latest . -f Dockerfile-mysql
            echo "PUSH"
            docker push $DOCKER_USERNAME/minitwit-app:latest
            docker push $DOCKER_USERNAME/minitwit-mysql:latest
      - run:
          name: Run pytest on build server
          command: |
            echo "Running Py tests...."
            docker build -t $DOCKER_USERNAME/minitwittestimage -f Dockerfile-minitwit-tests .
            echo "yes" | docker-compose up -d
            docker run -it --rm --network=itu-minitwit-network $DOCKER_USERNAME/minitwittestimage
#      - run:
#          name: Deploy app to Digital Ocean Server via Docker
#          command: |
#            ssh -o "StrictHostKeyChecking no" ${MT_USER}@${MT_SERVER} \
#            "source /root/.bash_profile && \
#            cd /vagrant && \
#            docker-compose pull && \
#            docker-compose up -d"
