## Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
#version: 2.1
#
## Use a package of configuration called an orb.
#orbs:
#
## Declare a dependency on the welcome-orb
#welcome: circleci/welcome-orb@0.4.1
#
## Orchestrate or schedule a set of jobs
#workflows:
#
## Name the workflow "welcome"
#welcome:
#
## Run the welcome/run job in its own container
#jobs:
#  - welcome/run


version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Run pytest
          command: |
           - echo "Running Py tests...."
           - docker build -t $DOCKER_USERNAME/minitwittestimage -f Dockerfile-minitwit-tests .
           - yes | docker-compose up -d
           - docker run -it --rm --network=itu-minitwit-network $DOCKER_USERNAME/minitwittestimage
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
           - echo "LOGIN"
           - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
           - echo "BUILD"
           - docker build -t $DOCKER_USERNAME/minitwit-app:latest . -f Dockerfile-minitwit
           - docker build -t $DOCKER_USERNAME/minitwit-mysql:latest . -f Dockerfile-mysql
           - echo "PUSH"
           - docker push $DOCKER_USERNAME/minitwit-app:latest
           - docker push $DOCKER_USERNAME/minitwit-mysql:latest
      - run:
          name: Deploy app to Digital Ocean Server via Docker
          command: |
            ssh -o "StrictHostKeyChecking no" ${MT_USER}@${MT_SERVER} \
            "source /root/.bash_profile && \
            cd /vagrant && \
            docker-compose pull && \
            docker-compose up -d && \
            docker pull $DOCKER_USERNAME/flagtoolimage:latest"
